import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'app.dart';
import 'shared/services/notification_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  // Note: Needs firebase_options.dart generated by flutterfire CLI
  try {
    await Firebase.initializeApp();
    // Register FCM background handler immediately after Firebase init.
    // Must be called before any other FCM work.
    await NotificationService.registerBackgroundHandler();
  } catch (e) {
    debugPrint('Firebase init error: $e');
  }

  runApp(const ProviderScope(child: StudyCompeteApp()));
}
